name: Behave Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install behave
        pip install wheel
        pip install flake8 pytest
    - name: Lint with flake8
      run: |
        flake8 --ignore=E501,F401
    - name: Install azurestoragewrapper and requirements
      run: |
        echo $PWD
        cd "/home/runner/work/AzureStorageWrapper/AzureStorageWrapper/main"
        echo $PWD
        ls -d */
        pip install .
        pip install -r requirements.txt

    - name: Run behave tests
      run: |
        pip list
        cd /opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/site-packages
        ls -d */
        cd "/home/runner/work/AzureStorageWrapper/AzureStorageWrapper/test"
        echo $PWD

        behave --tags @storage_wrapper_functions -D tenant_id=${{ secrets.tenantId }} -D vault_url=${{ secrets.vaultURL }} -D storage_account_app_id==${{ secrets.storageAccountAppId }} -D storage_account_app_key==${{ secrets.storageAccountAppKey }} -D storage_account_name==${{ secrets.storageAccountName }} -D container_name==${{ secrets.containerName }} --no-capture
